OPP2=./oppgave2/src/

all: oppvarming blackjack

oppvarming:
	g++ -std=c++11 ./oppgave1/src/oppvarming.cpp -o oppvarming

blackjack: 
	g++ -std=c++11 $(OPP2)blackjack.cpp $(OPP2)HumanIO.cpp $(OPP2)HPlayer.cpp $(OPP2)BetSize.cpp $(OPP2)Player.cpp $(OPP2)ScoreCalc.cpp $(OPP2)Bank.cpp $(OPP2)Game.cpp $(OPP2)Card.cpp $(OPP2)CardDeck.cpp $(OPP2)Strings.cpp $(OPP2)Test.cpp -o blackjack
